#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/font-sizes.sh"
cd "$SCRIPT_DIR/../builtinFonts"

# An ID is the sum of the face set's content hashes. Nothing persists it -- it is a
# compile-time handle that insertFont() and getBuiltinReaderFontId() have to agree on within
# one build, and nothing more. (src/fontIds.h had not in fact been regenerated since May
# despite the headers changing twice since, which is the proof that nothing downstream cares
# what the number is.) So the only real requirements are distinct and non-zero, and there is a
# static_assert on the latter in CrossPointSettings.cpp.
#
# Was a ruby one-liner; this is the same arithmetic in python, which the rest of the font
# pipeline already requires and which is therefore actually installed wherever the fonts get
# built. Note that ruby's File.read is text-mode on Windows and this is not, so the two agree
# only on LF input -- which is what fontconvert.py writes.
font_id() {
  python -c 'import hashlib,sys; print(sum(int(hashlib.sha256(open(f,"rb").read()).hexdigest(),16) for f in sys.argv[1:]) % (2 ** 32) - (2 ** 31))' "$@"
}

emit_ids() {  # emit_ids MACRO_PREFIX file_stem styles_array_name sizes...
  local macro="$1" stem="$2" styles_name="$3"
  shift 3
  local -n styles="$styles_name"
  local size style files
  for size in "$@"; do
    files=()
    for style in "${styles[@]}"; do
      files+=("./${stem}_${size}_$(echo "$style" | tr '[:upper:]' '[:lower:]').h")
    done
    echo "#define ${macro}_${size}_FONT_ID ($(font_id "${files[@]}"))"
  done
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

emit_ids BOOKERLY bookerly READER_FONT_STYLES "${BOOKERLY_FONT_SIZES[@]}"
emit_ids NOTOSANS notosans READER_FONT_STYLES "${NOTOSANS_FONT_SIZES[@]}"
emit_ids UI inter_ui UI_FONT_STYLES "${UI_ID_FONT_SIZES[@]}"

# Sizes drawn by scaling a master. Hashed from the MASTER's faces plus the point size, so the ID
# is still content-derived and still changes when the master is regenerated, while staying
# distinct from the master's own ID and from the other synthesised sizes.
synth_id() {  # synth_id pt file...
  local pt="$1"
  shift
  python -c 'import hashlib,sys
pt = sys.argv[1]
h = sum(int(hashlib.sha256(open(f,"rb").read()).hexdigest(), 16) for f in sys.argv[2:])
h += int(hashlib.sha256(("@" + pt + "pt").encode()).hexdigest(), 16)
print(h % (2 ** 32) - (2 ** 31))' "$pt" "$@"
}

emit_synth_ids() {  # emit_synth_ids MACRO_PREFIX file_stem
  local macro="$1" stem="$2" pt style files
  for pt in "${SYNTH_FONT_SIZES[@]}"; do
    files=()
    for style in "${READER_FONT_STYLES[@]}"; do
      files+=("./${stem}_${SYNTH_FONT_MASTER}_$(echo "$style" | tr '[:upper:]' '[:lower:]').h")
    done
    echo "#define ${macro}_${pt}_FONT_ID ($(synth_id "$pt" "${files[@]}"))"
  done
}

emit_synth_ids BOOKERLY bookerly
emit_synth_ids NOTOSANS notosans

# The status/footer font. One face, one size, not on the reader ladder.
echo "#define SMALL_FONT_ID ($(font_id ./notosans_8_regular.h))"
