// Correctness check for tinflate.c's LZ-copy hot path, run against both copy
// variants. This file is compiled twice -- once with
// UZLIB_CONF_USE_MEMCPY=0 (byte-by-byte) and once with =1 (bulk memcpy) -- into
// two separate test executables (see CMakeLists.txt), so the two variants never
// share a translation unit and there are no symbol clashes.
//
// The fixtures (zlib-compressed payloads + the FNV-1a-64 hash of their original
// bytes) are generated by scripts/gen_uzlib_fixtures.py. They span the LZ
// patterns that separate the variants -- in particular distance-1 overlapping
// runs, which the *unclamped* memcpy path decompresses incorrectly. So with the
// scripts/uzlib_patches fix applied this passes for both variants; without it,
// the memcpy build fails here -- which is the point of having it in CI. The
// byte-by-byte build never had the bug: its pass is the control that proves the
// fixtures and their hashes are valid, so a memcpy failure points at the copy.

#include <gtest/gtest.h>

#include <cstdint>
#include <cstring>
#include <vector>

#include "fixtures.h"
#include "uzlib.h"

#ifndef UZLIB_CONF_USE_MEMCPY
#define UZLIB_CONF_USE_MEMCPY 0
#endif

namespace {

const char* VariantName() { return UZLIB_CONF_USE_MEMCPY ? "memcpy" : "byte-by-byte"; }

// FNV-1a 64, matching scripts/gen_uzlib_fixtures.py.
uint64_t Fnv1a(const uint8_t* p, size_t n) {
  uint64_t h = 0xCBF29CE484222325ULL;
  for (size_t i = 0; i < n; i++) {
    h ^= p[i];
    h *= 0x100000001B3ULL;
  }
  return h;
}

// Inflate a full zlib stream into out[0..out_len) in one-shot whole-buffer mode
// -- the non-ring path guarded by UZLIB_CONF_USE_MEMCPY. Returns bytes produced.
size_t InflateOneShot(const unsigned char* comp, size_t comp_len, uint8_t* out, size_t out_len, int* result) {
  TINF_DATA d;
  memset(&d, 0, sizeof d);
  uzlib_uncompress_init(&d, nullptr, 0);
  d.source = comp;
  d.source_limit = comp + comp_len;
  d.source_read_cb = nullptr;
  uzlib_get_byte(&d);  // skip the 2-byte zlib header
  uzlib_get_byte(&d);
  d.dest_start = out;
  d.dest = out;
  d.dest_limit = out + out_len;
  *result = uzlib_uncompress(&d);
  return static_cast<size_t>(d.dest - out);
}

}  // namespace

TEST(UzlibLzCopy, DecompressesEveryFixtureCorrectly) {
  for (size_t i = 0; i < kUzlibFixtureCount; i++) {
    const UzlibFixture& fx = kUzlibFixtures[i];
    SCOPED_TRACE(testing::Message() << "variant=" << VariantName() << " fixture=" << fx.name);

    std::vector<uint8_t> out(fx.raw_len, 0xAA);
    int rc = 0;
    size_t produced = InflateOneShot(fx.comp, fx.comp_len, out.data(), out.size(), &rc);

    EXPECT_GE(rc, 0) << "uzlib_uncompress returned error " << rc;
    ASSERT_EQ(produced, fx.raw_len) << "produced wrong number of bytes";
    EXPECT_EQ(Fnv1a(out.data(), produced), fx.raw_fnv1a) << "decompressed bytes do not match the original payload";
  }
}
